name: Run daily_question.py at 7am IST

on:
  schedule:
    - cron: "30 1 * * *"   # 01:30 UTC = 07:00 IST, daily
  workflow_dispatch:        # allow manual run from Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    concurrency:
      group: daily-question
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python daily_question.py
